# Generated by Django 2.1 on 2018-10-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasdelivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
