# Generated by Django 2.1 on 2018-10-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('gasdelivers', '0002_auto_20181007_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('WL', 'WL'), ('COD', 'COD')], default='COD', max_length=2)),
                ('location', models.CharField(max_length=200)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='orders',
            name='Client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client'),
        ),
    ]
